/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author user
 */
public class TelaPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaComMenu
     */
    public TelaPagamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelRolagem = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        botaoCadastroCliente = new javax.swing.JButton();
        labeNome1 = new javax.swing.JLabel();
        campoNomePlano = new javax.swing.JTextField();
        labelTipoPagamento = new javax.swing.JLabel();
        campoTipoPagamento = new javax.swing.JComboBox<>();
        tabelaPagamento = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imagemFundo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuPlano = new javax.swing.JMenu();
        menuExercicio = new javax.swing.JMenu();
        menuAvaliacao = new javax.swing.JMenu();
        menuPagamento = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelValor.setForeground(new java.awt.Color(255, 255, 255));
        labelValor.setText("Valor:");
        painelPrincipal.add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 98, 35));

        campoValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 617, -1));

        botaoCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoCadastroCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\drive_9905238.png")); // NOI18N
        botaoCadastroCliente.setText("Cadastrar Pagamento");
        painelPrincipal.add(botaoCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 320, 60));

        labeNome1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeNome1.setForeground(new java.awt.Color(255, 255, 255));
        labeNome1.setText("Nome do aluno:");
        painelPrincipal.add(labeNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 350, 230, 35));

        campoNomePlano.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoNomePlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 617, -1));

        labelTipoPagamento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTipoPagamento.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoPagamento.setText("Tipo pagamento:");
        painelPrincipal.add(labelTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 210, 35));

        campoTipoPagamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Dinheiro", "Cartão de Crédito", "Cartão Débito", " " }));
        painelPrincipal.add(campoTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Valor", "Vencimento", "Tipo Pagamento", "Data Pagamento"
            }
        ));
        tabelaPagamento.setViewportView(jTable1);

        painelPrincipal.add(tabelaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 1010, -1));

        imagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\capaPagamento.png")); // NOI18N
        painelPrincipal.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painelRolagem.setViewportView(painelPrincipal);

        menuHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\botao-de-inicio.png")); // NOI18N
        menuHome.setText("Home");
        barraMenu.add(menuHome);

        menuPlano.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\de-dinheiro.png")); // NOI18N
        menuPlano.setText("Planos");
        barraMenu.add(menuPlano);

        menuExercicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\exercicio.png")); // NOI18N
        menuExercicio.setText("Exercicios");
        barraMenu.add(menuExercicio);

        menuAvaliacao.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\ioga.png")); // NOI18N
        menuAvaliacao.setText("Avaliação Física");
        barraMenu.add(menuAvaliacao);

        menuPagamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\forma-de-pagamento.png")); // NOI18N
        menuPagamento.setText("Pagamentos");
        barraMenu.add(menuPagamento);

        menuRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\relatorio-de-venda.png")); // NOI18N
        menuRelatorio.setText("Relatórios");
        barraMenu.add(menuRelatorio);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCadastroCliente;
    private javax.swing.JTextField campoNomePlano;
    private javax.swing.JComboBox<String> campoTipoPagamento;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeNome1;
    private javax.swing.JLabel labelTipoPagamento;
    private javax.swing.JLabel labelValor;
    private javax.swing.JMenu menuAvaliacao;
    private javax.swing.JMenu menuExercicio;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuPlano;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane painelRolagem;
    private javax.swing.JScrollPane tabelaPagamento;
    // End of variables declaration//GEN-END:variables
}
