/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author user
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaComMenu
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelRolagem = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        labeNome = new javax.swing.JLabel();
        labeCpf = new javax.swing.JLabel();
        labeTelefone = new javax.swing.JLabel();
        campoNomeAluno = new javax.swing.JTextField();
        campoCpfAluno = new javax.swing.JFormattedTextField();
        campoTelefone = new javax.swing.JFormattedTextField();
        botaoCadastroCliente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelPlano = new javax.swing.JLabel();
        tabelaClientes = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelPlano1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        labelPesquisa = new javax.swing.JLabel();
        campoPesquisa = new javax.swing.JTextField();
        botaoEditarCliente = new javax.swing.JButton();
        botaoExcluirCliente = new javax.swing.JButton();
        labeNome1 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuPlano = new javax.swing.JMenu();
        menuExercicio = new javax.swing.JMenu();
        menuAvaliacao = new javax.swing.JMenu();
        menuPagamento = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeNome.setForeground(new java.awt.Color(255, 255, 255));
        labeNome.setText("Cadastrar Aluno");
        painelPrincipal.add(labeNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 280, 35));

        labeCpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeCpf.setForeground(new java.awt.Color(255, 255, 255));
        labeCpf.setText("CPF:");
        painelPrincipal.add(labeCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 98, 35));

        labeTelefone.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labeTelefone.setText("Telefone:");
        painelPrincipal.add(labeTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 138, 35));

        campoNomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 617, -1));

        try {
            campoCpfAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCpfAluno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoCpfAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 617, -1));

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 577, -1));

        botaoCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoCadastroCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\drive_9905238.png")); // NOI18N
        botaoCadastroCliente.setText("Cadastrar");
        painelPrincipal.add(botaoCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 750, 200, 60));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x na semana", "4x na semana", "5x na semana" }));
        painelPrincipal.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 242, -1));

        labelPlano.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPlano.setForeground(new java.awt.Color(255, 255, 255));
        labelPlano.setText("Plano:");
        painelPrincipal.add(labelPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 138, 35));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone", "Plano", "Data Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.setViewportView(jTable1);

        painelPrincipal.add(tabelaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 829, 510));

        labelPlano1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPlano1.setForeground(new java.awt.Color(255, 255, 255));
        labelPlano1.setText("Dia Pagamento:");
        painelPrincipal.add(labelPlano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 235, 35));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        painelPrincipal.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, -1, -1));

        labelPesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\lupa.png")); // NOI18N
        painelPrincipal.add(labelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 310, -1, -1));

        campoPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoPesquisa.setText("Pesquise pelo nome ou CPF");
        painelPrincipal.add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 301, 420, 50));

        botaoEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoEditarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\ui-element_15768411.png")); // NOI18N
        botaoEditarCliente.setText("Editar");
        painelPrincipal.add(botaoEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 750, 190, 60));

        botaoExcluirCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoExcluirCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\bin_2602735.png")); // NOI18N
        botaoExcluirCliente.setText("Excluir");
        botaoExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirClienteActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 750, 190, 60));

        labeNome1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeNome1.setForeground(new java.awt.Color(255, 255, 255));
        labeNome1.setText("Nome: ");
        painelPrincipal.add(labeNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 98, 35));

        imagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\capaHome.png")); // NOI18N
        painelPrincipal.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painelRolagem.setViewportView(painelPrincipal);

        menuHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\botao-de-inicio.png")); // NOI18N
        menuHome.setText("Home");
        barraMenu.add(menuHome);

        menuPlano.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\de-dinheiro.png")); // NOI18N
        menuPlano.setText("Planos");
        barraMenu.add(menuPlano);

        menuExercicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\exercicio.png")); // NOI18N
        menuExercicio.setText("Exercicios");
        barraMenu.add(menuExercicio);

        menuAvaliacao.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\ioga.png")); // NOI18N
        menuAvaliacao.setText("Avaliação Física");
        barraMenu.add(menuAvaliacao);

        menuPagamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\forma-de-pagamento.png")); // NOI18N
        menuPagamento.setText("Pagamentos");
        barraMenu.add(menuPagamento);

        menuRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\relatorio-de-venda.png")); // NOI18N
        menuRelatorio.setText("Relatórios");
        barraMenu.add(menuRelatorio);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCadastroCliente;
    private javax.swing.JButton botaoEditarCliente;
    private javax.swing.JButton botaoExcluirCliente;
    private javax.swing.JFormattedTextField campoCpfAluno;
    private javax.swing.JTextField campoNomeAluno;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeCpf;
    private javax.swing.JLabel labeNome;
    private javax.swing.JLabel labeNome1;
    private javax.swing.JLabel labeTelefone;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JLabel labelPlano;
    private javax.swing.JLabel labelPlano1;
    private javax.swing.JMenu menuAvaliacao;
    private javax.swing.JMenu menuExercicio;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuPlano;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane painelRolagem;
    private javax.swing.JScrollPane tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
