/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author user
 */
public class TelaPanos extends javax.swing.JFrame {

    /**
     * Creates new form TelaComMenu
     */
    public TelaPanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelRolagem = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        botaoCadastroCliente = new javax.swing.JButton();
        botaoEditarCliente = new javax.swing.JButton();
        botaoExcluirCliente = new javax.swing.JButton();
        labeNome1 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        campoNomePlano = new javax.swing.JTextField();
        campoEscolhaPlano = new javax.swing.JComboBox<>();
        imagemFundo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuPlano = new javax.swing.JMenu();
        menuExercicio = new javax.swing.JMenu();
        menuAvaliacao = new javax.swing.JMenu();
        menuPagamento = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelValor.setForeground(new java.awt.Color(255, 255, 255));
        labelValor.setText("Valor:");
        painelPrincipal.add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 98, 35));

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(255, 255, 255));
        labelDescricao.setText("Descrição:");
        painelPrincipal.add(labelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 138, 35));

        campoValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 617, -1));

        botaoCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoCadastroCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\drive_9905238.png")); // NOI18N
        botaoCadastroCliente.setText("Cadastrar");
        painelPrincipal.add(botaoCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 860, 200, 60));

        botaoEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoEditarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\ui-element_15768411.png")); // NOI18N
        botaoEditarCliente.setText("Editar");
        painelPrincipal.add(botaoEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 860, 190, 60));

        botaoExcluirCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoExcluirCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\bin_2602735.png")); // NOI18N
        botaoExcluirCliente.setText("Excluir");
        botaoExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirClienteActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 860, 190, 60));

        labeNome1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeNome1.setForeground(new java.awt.Color(255, 255, 255));
        labeNome1.setText("Nome: ");
        painelPrincipal.add(labeNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 98, 35));

        campoDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        campoDescricao.setViewportView(jTextArea1);

        painelPrincipal.add(campoDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 620, 260));

        campoNomePlano.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        painelPrincipal.add(campoNomePlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 617, -1));

        campoEscolhaPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um plano" }));
        painelPrincipal.add(campoEscolhaPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 350, 230, 40));

        imagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\capaPlanos.png")); // NOI18N
        painelPrincipal.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painelRolagem.setViewportView(painelPrincipal);

        menuHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\botao-de-inicio.png")); // NOI18N
        menuHome.setText("Home");
        barraMenu.add(menuHome);

        menuPlano.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\de-dinheiro.png")); // NOI18N
        menuPlano.setText("Planos");
        barraMenu.add(menuPlano);

        menuExercicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\exercicio.png")); // NOI18N
        menuExercicio.setText("Exercicios");
        barraMenu.add(menuExercicio);

        menuAvaliacao.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\ioga.png")); // NOI18N
        menuAvaliacao.setText("Avaliação Física");
        barraMenu.add(menuAvaliacao);

        menuPagamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\forma-de-pagamento.png")); // NOI18N
        menuPagamento.setText("Pagamentos");
        barraMenu.add(menuPagamento);

        menuRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\relatorio-de-venda.png")); // NOI18N
        menuRelatorio.setText("Relatórios");
        barraMenu.add(menuRelatorio);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCadastroCliente;
    private javax.swing.JButton botaoEditarCliente;
    private javax.swing.JButton botaoExcluirCliente;
    private javax.swing.JScrollPane campoDescricao;
    private javax.swing.JComboBox<String> campoEscolhaPlano;
    private javax.swing.JTextField campoNomePlano;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeNome1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelValor;
    private javax.swing.JMenu menuAvaliacao;
    private javax.swing.JMenu menuExercicio;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuPlano;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane painelRolagem;
    // End of variables declaration//GEN-END:variables
}
